# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transit < Formula
  desc "CLI tool that interacts with local transit information"
  homepage "https://transitcli.com/"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Darwin_arm64.tar.gz"
      sha256 "147a51f44a9f058ba171ae889d484dcba9969c2a05fe9dce70dccfb6421a2e9a"

      def install
        bin.install "transit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Linux_arm64.tar.gz"
      sha256 "817250a169a68ec3d121a522caa41eddb2d7e0aa422f923dec33c8e952c2cd25"

      def install
        bin.install "transit"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transit --version")
  end
end
