# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transit < Formula
  desc "CLI tool that interacts with local transit information"
  homepage "https://transitcli.com/"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Darwin_arm64.tar.gz"
      sha256 "7a952135a4f46ed993cb984a28a5525640a80dfef0d1a75d7704aecabd985f2f"

      def install
        bin.install "transit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Linux_arm64.tar.gz"
      sha256 "63b468f1c4689e1f01b5d08f10794e75692f0b7d70de223e3cd51e19c22d5b3f"

      def install
        bin.install "transit"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transit --version")
  end
end
