# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transit < Formula
  desc "CLI tool that interacts with local transit information"
  homepage "https://transitcli.com"
  version "1.2.2"
  license "MIT"

  on_macos do
    url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Darwin_all.tar.gz"
    sha256 "1341a75bfa64ecc234935f16163f34a797f2f1f04a4053478a05d2c2e32d3ca6"

    def install
      bin.install "transit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Linux_armv7.tar.gz"
      sha256 "afaff14f68aed40007ec76299a76605b4cbced81c36d891749e6192d3bdc0c24"

      def install
        bin.install "transit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Linux_x86_64.tar.gz"
      sha256 "009c652d1ac214290fe9ab6fd4d46cc36e562116ceefad144915185feb8f3263"

      def install
        bin.install "transit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ismailshak/transit/releases/download/v1.2.2/transit_Linux_arm64.tar.gz"
      sha256 "470b72ab25f62c2bf048e5b492168d3332d3b60e29650c74e60509b8f5c7fb52"

      def install
        bin.install "transit"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transit --version")
  end
end
